#include "sd/sd_ext.h"
#include "sd/sd_incl.h"

int            sd_debug_mode;
int            song_loop_count;
unsigned int   key_fg;
int            sd_code_set;
int            sng_syukan_vol;
int            sng_fadein_time;
int            vox_on_vol;
int            sng_fout_fg;
int            sd_code_read;
int            sng_kaihi_fg;
int            sng_pause_fg;
SOUND_W        sound_w[SD_N_VOICES];
int            sng_fadein_fg;
int            sng_fade_time[SD_BGM_VOICES];
int            sng_syukan_fg;
int            sng_fout_term;
int            sng_fade_value[SD_BGM_VOICES];
int            se_tracks;
int            sd_sng_code_buf[16];
int            eons[2];
SEPLAYTBL      se_playing[SD_SE_VOICES];
unsigned int   mdata1;
unsigned int   mdata2;
unsigned int   mdata3;
unsigned int   mdata4;
SEPLAYTBL      se_request[SD_SE_VOICES];
int            sng_status;
int            stop_jouchuu_se;
int            se_pan[SD_SE_VOICES];
unsigned int   mtrack;
int            se_vol[SD_SE_VOICES];
int            eoffs[2];
unsigned int   keyons[2];
unsigned char *se_data;
unsigned char *se_exp_data;
unsigned char *se_exp_table;
SETBL         *se_header;
SETBL         *se_exp_header;
unsigned int   keyoffs[2];
unsigned char  sng_data[0x20000];
unsigned int   song_end[2];
unsigned int   song_loop_end[2];
unsigned int   sng_play_code;
int            sound_mono_fg;
unsigned int   keyd[2];
unsigned char  se_data_area[0x7000];
unsigned char  se_exp_data_area[0x4800];
WAVE_W         voice_tbl[512];
WAVE_W         drum_tbl[64];
unsigned char *mptr;
int            se_rev_on;
SOUND_W       *sptr;
SPU_TRACK_REG  spu_tr_wk[SD_N_VOICES];
unsigned int   sng_master_vol[SD_BGM_VOICES];
unsigned int   skip_intro_loop;
FADER          mix_fader[SD_BGM_VOICES];
unsigned int   auto_phase_fg;
unsigned char  auto_env_pos;
unsigned char  auto_env_pos2;
MEM_STR_W      mem_str_w[SD_SE_VOICES];
unsigned char  mem_str_buf[524288];
int            fg_rev_set[SD_N_VOICES];
